Validations
BiancaMe/my-sheeps-blog pull request #4
Opened 2023-11-18 20:38 UTC by BiancaMe

Add the following validations:

For the User model:
-Name must not be blank.
-PostsCounter must be an integer greater than or equal to zero.

For the Post model:
-Title must not be blank.
-Title must not exceed 250 characters.
-CommentsCounter must be an integer greater than or equal to zero.
-LikesCounter must be an integer greater than or equal to zero.

Add unit specs for all of your models' methods and validations.

2023-11-18 21:07 UTC, OyePriscilla requested changes
Hi @BiancaMe 👏 👏 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Implemented validations for models. ✔️ 
Implemented unit tests for models. ✔️ 
All tests passed. ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-18 21:07 UTC, OyePriscilla commented on spec/models/user_spec.rb
> +  end
- [ ] In accordance to the project requirement, kindly implement test for the user's model's method highlighted from your codebase. 👇 

```
 def recents(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end
```

<img width="419" alt="Untitled" src="https://github.com/BiancaMe/my-sheeps-blog/assets/103386183/e7a02342-d36a-4389-8c74-84a89a7cad1a">

2023-11-18 21:07 UTC, OyePriscilla commented on spec/models/post_spec.rb
> +
- [ ] In accordance to the project requirement, kindly implement test for the post's model's method highlighted from your codebase. 👇 

```
 def recents(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end
```

<img width="419" alt="Untitled" src="https://github.com/BiancaMe/my-sheeps-blog/assets/103386183/e7a02342-d36a-4389-8c74-84a89a7cad1a">

2023-11-20 08:05 UTC, TedLivist reviewed
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @BiancaMe,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Kindly submit a fresh PR, without reviewer comments, since this was not approved for the previous week.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-11-22 13:03 UTC, closed without merging